services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrong!Passw0rd
    ports:
      - "1434:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app_network

  mongodb:
    image: mongodb/mongodb-community-server:7.0.5-ubuntu2204
    container_name: mongodb_server
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mssql_data:
  mongo_data:

networks:
  app_network:
    driver: bridge
