services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  mongodb:
    image: mongodb/mongodb-community-server:7.0.5-ubuntu2204
    container_name: mongodb_server
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app_network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrong!Passw0rd
    ports:
      - "1434:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app_network

# Was trying to automate the initialization of the mssql db as well but sqlcmd is not in the path and i don't know where it is 
# or if this is even the way to do it.
  # mssql-tools:
  #   image: mcr.microsoft.com/mssql-tools:latest
  #   container_name: mssql-tools
  #   restart: no
  #   command: "/opt/mssql-tools18/bin/sqlcmd -S mssql_server -l 60 -U sa -P 'MyStrong!Passw0rd' -d master -i /tmp/mssql-init.sql"
  #   depends_on:
  #     - mssql
  #   volumes:
  #     - ./mssql-init.sql:/tmp/mssql-init.sql
  #   networks:
  #     - app_network

  book_store_app:
    build: 
      context: .
      dockerfile: BookStoreApp/Dockerfile
    container_name: bookstore_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - redis
      - mongodb
      - mssql
    networks:
      - app_network

volumes:
  mssql_data:
  mongo_data:

networks:
  app_network:
    driver: bridge
